### ISSUE TITLE
OSError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by ciweiin** [abbeyokgo/Atc#1]
[2019-01-16 08:12:30 +0000] [20180] [INFO] Starting gunicorn 19.9.0
[2019-01-16 08:12:30 +0000] [20180] [INFO] Listening at: http://0.0.0.0:35000 (20180)
[2019-01-16 08:12:30 +0000] [20180] [INFO] Using worker: eventlet
[2019-01-16 08:12:30 +0000] [20187] [INFO] Booting worker with pid: 20187
checking if login
load cookies and login success
[2019-01-16 08:12:53 +0000] [20187] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 66, in handle
    six.reraise(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 129, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 112, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 403, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 393, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 66, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 11] Resource temporarily unavailable

**Comment by 2024baibai** [comment]
https://www.abbeyok.com/archives/244
